### ISSUE TITLE
AttributeError: 'IntegerField' object has no attribute 'rel'

### ISSUE THREAD

**Issue by nint8835** [toobigtoignore/issf#100]
Loading profiles produces a 500 internal server error in the console. 

Server console log:
```
web_1      | Internal Server Error: /frontend/map-data/
web_1      | Traceback (most recent call last):
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
web_1      |     response = get_response(request)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 128, in _get_response
web_1      |     response = self.process_exception_by_middleware(e, request)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
web_1      |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1      |   File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner
web_1      |     return func(*args, **kwds)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 69, in view
web_1      |     return self.dispatch(request, *args, **kwargs)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 62, in _wrapper
web_1      |     return bound_func(*args, **kwargs)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
web_1      |     response = view_func(request, *args, **kwargs)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 58, in bound_func
web_1      |     return func.__get__(self, type(self))(*args2, **kwargs2)
web_1      |   File "/usr/local/lib/python3.7/site-packages/djgeojson/views.py", line 79, in dispatch
web_1      |     return super(GeoJSONLayerView, self).dispatch(*args, **kwargs)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 89, in dispatch
web_1      |     return handler(request, *args, **kwargs)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/views/generic/list.py", line 158, in get
web_1      |     return self.render_to_response(context)
web_1      |   File "/usr/local/lib/python3.7/site-packages/djgeojson/views.py", line 69, in render_to_response
web_1      |     **options)
web_1      |   File "/usr/local/lib/python3.7/site-packages/djgeojson/serializers.py", line 460, in serialize
web_1      |     self.serialize_queryset(queryset)
web_1      |   File "/usr/local/lib/python3.7/site-packages/djgeojson/serializers.py", line 416, in serialize_queryset
web_1      |     if field.rel is None:
web_1      | AttributeError: 'IntegerField' object has no attribute 'rel'
```

Nothing is broken by this at the first glance, but this should still be looked at.

**Comment by jackharrhy** [comment]
Seems to be related to:

https://code.djangoproject.com/ticket/24317

Might require an update to:

https://github.com/makinacorpus/django-geojson

**Comment by nint8835** [comment]
Appears to have been resolved by PR #107

**Comment by nint8835** [comment]
Just had the error occur on a fresh build of the image when trying to create a SSF Profile.

**Comment by nint8835** [comment]
Issue appears to have been due to the tbti/web image having not been rebuilt. As a result, this issue is now fixed.
