### ISSUE TITLE
Unable to create any item that relies on geographic scope

### ISSUE THREAD

**Issue by nint8835** [toobigtoignore/issf#89]
**Describe the bug**
Contributing an item that requires you to input a geographic scope does not work and produces two errors depending on the type of scope you select

**To Reproduce**
1. Click contribute
2. Click on an item that requires a geographic scope (such as an organization)
3. Fill out the required items and click submit
4. Fill out the geographic scope
5. Click submit

**Expected behavior**
It should continue to the next page

**Actual behavior**
One of two errors occur:

- Geographic scope of national
    - Submission fails due to an internal server error (DB complains that column doesn't exist)
- Any other geographic scope
    - Submission fails with the issue `An invalid form control with name='countries' is not focusable.`

**Comment by jackharrhy** [comment]
Potentially relates to https://github.com/toobigtoignore/issf/pull/54

In that things like `forms.DateField()` that are now required must now be `forms.DateField(required=False)`.

A reason this might be is due to this error:

"An invalid form control with name='countries' is not focusable."

It's trying to focus on a element that isn't currently being rendered, and it wants to focus on it because it wants to tell the user to fill in this element, but obviously this is not a form control for whatever the user is currently doing.

This probably doesn't fix "Submission fails due to an internal server error (DB complains that column doesn't exist)".

**Comment by jackharrhy** [comment]
Context required from @ranguli for the database related issue.

**Comment by nint8835** [comment]
Non-national geographic scope has been fixed in commit a7f47420f94cae9117159baadc20981db35bf13f via Jack's suggested fix.

**Comment by nint8835** [comment]
National geographic scope produces the following console output:

```
web_1      | Internal Server Error: /details/geographic-scope/
web_1      | Traceback (most recent call last):
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
web_1      |     return self.cursor.execute(sql, params)
web_1      | psycopg2.ProgrammingError: column geographic_scope_nation.id does not exist
web_1      | LINE 1: ...e_id", "country_id") VALUES (3606, 175) RETURNING "geographi...
web_1      |                                                              ^
web_1      |
web_1      |
web_1      | The above exception was the direct cause of the following exception:
web_1      |
web_1      | Traceback (most recent call last):
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
web_1      |     response = get_response(request)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 128, in _get_response
web_1      |     response = self.process_exception_by_middleware(e, request)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
web_1      |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1      |   File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner
web_1      |     return func(*args, **kwds)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
web_1      |     return view_func(request, *args, **kwargs)
web_1      |   File "/issf/apps/details/views.py", line 1401, in geographic_scope
web_1      |     nation_form.save()
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/forms/models.py", line 457, in save
web_1      |     self._save_m2m()
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/forms/models.py", line 439, in _save_m2m
web_1      |     f.save_form_data(self.instance, cleaned_data[f.name])
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/related.py", line 1619, in save_form_data
web_1      |     getattr(instance, self.attname).set(data)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 969, in set
web_1      |     self.add(*new_objs)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 898, in add
web_1      |     self._add_items(self.source_field_name, self.target_field_name, *objs)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 1065, in _add_items
web_1      |     for obj_id in new_ids
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 466, in bulk_create
web_1      |     ids = self._batched_insert(objs_without_pk, fields, batch_size)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1142, in _batched_insert
web_1      |     inserted_id = self._insert(item, fields=fields, using=self.db, return_id=True)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1125, in _insert
web_1      |     return query.get_compiler(using=using).execute_sql(return_id)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1281, in execute_sql
web_1      |     cursor.execute(sql, params)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
web_1      |     return super().execute(sql, params)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
web_1      |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
web_1      |     return executor(sql, params, many, context)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
web_1      |     return self.cursor.execute(sql, params)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
web_1      |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
web_1      |     return self.cursor.execute(sql, params)
web_1      | django.db.utils.ProgrammingError: column geographic_scope_nation.id does not exist
web_1      | LINE 1: ...e_id", "country_id") VALUES (3606, 175) RETURNING "geographi...
web_1      |                                                              ^
web_1      |
db_1       | ERROR:  column geographic_scope_nation.id does not exist at character 99
db_1       | STATEMENT:  INSERT INTO "geographic_scope_nation" ("issf_core_id", "country_id") VALUES (3606, 175) RETURNING "geographic_scope_nation"."id"
db_1       | ERROR:  column geographic_scope_nation.id does not exist at character 8
db_1       | STATEMENT:  SELECT "geographic_scope_nation"."id", "geographic_scope_nation"."issf_core_id", "geographic_scope_nation"."country_id" FROM "geographic_scope_nation" LIMIT 21
db_1       | ERROR:  column geographic_scope_nation.id does not exist at character 8
db_1       | STATEMENT:  SELECT "geographic_scope_nation"."id", "geographic_scope_nation"."issf_core_id", "geographic_scope_nation"."country_id" FROM "geographic_scope_nation" LIMIT 21
```

**Comment by ranguli** [comment]
After running with different database dumps, I can confirm the issue is independent of the database used and must be code-related.

**Comment by nint8835** [comment]
Adjusting the model used from ISSF_Core to GeographicScopeNation solved this issue, but revealed an additional issue (issue #119), which will be continued in a separate issue.
